export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYERS_RESPONSE = 'GET_PLAYERS_RESPONSE';
export const SUCCESSFUL_CONNECTION = 'SUCCESSFUL_CONNECTION';
export const SET_PLAYER_VOLUME_REQUEST = 'SET_PLAYER_VOLUME_REQUEST';
export const PLAYER_VOLUME_CHANGED = 'PLAYER_VOLUME_CHANGED';