export const PLAY_STATE_REQUEST = 'PLAY_STATE_REQUEST';
export const PLAY_STATE_RESPONSE = 'PLAY_STATE_RESPONSE';
export const PLAY_STATE_CHANGED = 'PLAY_STATE_CHANGED';
export const TOGGLE_PLAY_PAUSE_REQUEST = 'TOGGLE_PLAY_PAUSE_REQUEST';
export const NEXT_TRACK_REQUEST = 'NEXT_TRACK_REQUEST';
export const PREVIOUS_TRACK_REQUEST = 'PREVIOUS_TRACK_REQUEST';
