module.exports = {
  FETCH_DEVICES_REQUEST: 'FETCH_DEVICES_REQUEST',
  FETCH_DEVICES_RESPONSE: 'FETCH_DEVICES_RESPONSE',
  NEW_DEVICE_DISCOVERED: 'NEW_DEVICE_DISCOVERED',
  CONNECT_TO_DEVICE: 'CONNECT_TO_DEVICE',
  SUCCESSFUL_CONNECTION: 'SUCCESSFUL_CONNECTION',
  TRACK_CHANGED: 'TRACK_CHANGED'
};